//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen DATEXII_3_EnergyInfrastructure.xsd -v --namespace http://datex2.eu/schema/3/common=Datex2ToOcpi.Core.Models.Datex2.Common --namespace http://datex2.eu/schema/3/commonExtension=Datex2ToOcpi.Core.Models.Datex2.CommonExtension --namespace http://datex2.eu/schema/3/facilities=Datex2ToOcpi.Core.Models.Datex2.Facilities --namespace http://datex2.eu/schema/3/energyInfrastructure=Datex2ToOcpi.Core.Models.Datex2.EnergyInfrastructure --namespace http://datex2.eu/schema/3/locationExtension=Datex2ToOcpi.Core.Models.Datex2.LocationExtension --namespace http://datex2.eu/schema/3/locationReferencing=Datex2ToOcpi.Core.Models.Datex2.LocationReferencing --namespace http://datex2.eu/schema/3/trafficRegulation=Datex2ToOcpi.Core.Models.Datex2.TrafficRegulation
namespace Datex2ToOcpi.Core.Models.Datex2.CommonExtension
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DayWeekMonthExtended", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DayWeekMonthExtended
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("applicableDaysWithinMonth")]
        public ApplicableDaysWithinMonthEnum ApplicableDaysWithinMonth { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_ApplicableDaysWithinMonthEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplicableDaysWithinMonthEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ApplicableDaysWithinMonthEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ApplicableDaysWithinMonthEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    public enum ApplicableDaysWithinMonthEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("evenDay")]
        EvenDay,

        [System.Xml.Serialization.XmlEnumAttribute("oddDay")]
        OddDay,

        [System.Xml.Serialization.XmlEnumAttribute("daysFromOneToFifteen")]
        DaysFromOneToFifteen,

        [System.Xml.Serialization.XmlEnumAttribute("daysFromSixteenToThirtyOne")]
        DaysFromSixteenToThirtyOne,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PeriodExtended", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeriodExtended
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FuzzyPeriod> _fuzzyPeriod;

        [System.Xml.Serialization.XmlElementAttribute("fuzzyPeriod")]
        public System.Collections.ObjectModel.Collection<FuzzyPeriod> FuzzyPeriod
        {
            get
            {
                return _fuzzyPeriod;
            }
            private set
            {
                _fuzzyPeriod = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FuzzyPeriod collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FuzzyPeriodSpecified
        {
            get
            {
                return (this.FuzzyPeriod.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PeriodExtended" /> class.</para>
        /// </summary>
        public PeriodExtended()
        {
            this._fuzzyPeriod = new System.Collections.ObjectModel.Collection<FuzzyPeriod>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FuzzyPeriod", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuzzyPeriod
    {

        [System.Xml.Serialization.XmlElementAttribute("beginOrDuration")]
        public FuzzyTimeEnum BeginOrDuration { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("endOrDuration")]
        public FuzzyTimeEnum EndOrDuration { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_fuzzyPeriodExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType FuzzyPeriodExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_FuzzyTimeEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuzzyTimeEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public FuzzyTimeEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FuzzyTimeEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    public enum FuzzyTimeEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("dawn")]
        Dawn,

        [System.Xml.Serialization.XmlEnumAttribute("sunset")]
        Sunset,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EmissionsExtension", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmissionsExtension
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("comparisonOperator")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ComparisonOperatorEnum ComparisonOperator { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VehicleCharacteristicsExtended", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VehicleCharacteristicsExtended
    {

        [System.Xml.Serialization.XmlElementAttribute("ageCharacteristic")]
        public AgeCharacteristic AgeCharacteristic { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("maximumDesignSpeed")]
        public Datex2ToOcpi.Core.Models.Datex2.TrafficRegulation.Speed MaximumDesignSpeed { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("trailerCharacteristics")]
        public TrailerCharacteristics TrailerCharacteristics { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("hazardousMaterials")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.HazardousMaterials HazardousMaterials { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EnginePowerCharacteristics> _enginePowerCharacteristics;

        [System.Xml.Serialization.XmlElementAttribute("enginePowerCharacteristics")]
        public System.Collections.ObjectModel.Collection<EnginePowerCharacteristics> EnginePowerCharacteristics
        {
            get
            {
                return _enginePowerCharacteristics;
            }
            private set
            {
                _enginePowerCharacteristics = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the EnginePowerCharacteristics collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnginePowerCharacteristicsSpecified
        {
            get
            {
                return (this.EnginePowerCharacteristics.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VehicleCharacteristicsExtended" /> class.</para>
        /// </summary>
        public VehicleCharacteristicsExtended()
        {
            this._enginePowerCharacteristics = new System.Collections.ObjectModel.Collection<EnginePowerCharacteristics>();
            this._regulatedCharacteristics = new System.Collections.ObjectModel.Collection<RegulatedCharacteristics>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RegulatedCharacteristics> _regulatedCharacteristics;

        [System.Xml.Serialization.XmlElementAttribute("regulatedCharacteristics")]
        public System.Collections.ObjectModel.Collection<RegulatedCharacteristics> RegulatedCharacteristics
        {
            get
            {
                return _regulatedCharacteristics;
            }
            private set
            {
                _regulatedCharacteristics = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RegulatedCharacteristics collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegulatedCharacteristicsSpecified
        {
            get
            {
                return (this.RegulatedCharacteristics.Count != 0);
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AgeCharacteristic", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgeCharacteristic
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("comparisonOperator")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ComparisonOperatorEnum ComparisonOperator { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("yearOfFirstRegistration")]
        public string YearOfFirstRegistration { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_ageCharacteristicExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType AgeCharacteristicExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TrailerCharacteristics", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrailerCharacteristics
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("grossTrailerWeightCharacteristics")]
        public GrossTrailerWeightCharacteristics GrossTrailerWeightCharacteristics { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_trailerCharacteristicsExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType TrailerCharacteristicsExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GrossTrailerWeightCharacteristics", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrossTrailerWeightCharacteristics
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("comparisonOperator")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ComparisonOperatorEnum ComparisonOperator { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("grossTrailerWeight")]
        public float GrossTrailerWeight { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("typeOfWeight")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.WeightTypeEnum TypeOfWeight { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_grossTrailerWeightCharacteristicsExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType GrossTrailerWeightCharacteristicsExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DangerousGoodsExtended", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DangerousGoodsExtended
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _adrClassValue;

        [System.Xml.Serialization.XmlElementAttribute("adrClassValue")]
        public System.Collections.ObjectModel.Collection<string> AdrClassValue
        {
            get
            {
                return _adrClassValue;
            }
            private set
            {
                _adrClassValue = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AdrClassValue collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrClassValueSpecified
        {
            get
            {
                return (this.AdrClassValue.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DangerousGoodsExtended" /> class.</para>
        /// </summary>
        public DangerousGoodsExtended()
        {
            this._adrClassValue = new System.Collections.ObjectModel.Collection<string>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EnginePowerCharacteristics", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnginePowerCharacteristics
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("comparisonOperator")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ComparisonOperatorEnum ComparisonOperator { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("enginePower")]
        public float EnginePower { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("unitOfMeasure")]
        public PowerUnitOfMeasureEnum UnitOfMeasure { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_enginePowerCharacteristicsExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType EnginePowerCharacteristicsExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_PowerUnitOfMeasureEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PowerUnitOfMeasureEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public PowerUnitOfMeasureEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PowerUnitOfMeasureEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    public enum PowerUnitOfMeasureEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("kilowatt")]
        Kilowatt,

        [System.Xml.Serialization.XmlEnumAttribute("horsepower")]
        Horsepower,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RegulatedCharacteristics", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegulatedCharacteristics
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EuVehicleCategoryEnum> _euVehicleCategory;

        [System.Xml.Serialization.XmlElementAttribute("euVehicleCategory")]
        public System.Collections.ObjectModel.Collection<EuVehicleCategoryEnum> EuVehicleCategory
        {
            get
            {
                return _euVehicleCategory;
            }
            private set
            {
                _euVehicleCategory = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the EuVehicleCategory collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EuVehicleCategorySpecified
        {
            get
            {
                return (this.EuVehicleCategory.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RegulatedCharacteristics" /> class.</para>
        /// </summary>
        public RegulatedCharacteristics()
        {
            this._euVehicleCategory = new System.Collections.ObjectModel.Collection<EuVehicleCategoryEnum>();
        }

        [System.Xml.Serialization.XmlElementAttribute("euSpecialPurposeVehicle")]
        public EuSpecialPurposeVehicleEnum EuSpecialPurposeVehicle { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("nationalSpecialPurposeVehicle")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.MultilingualString NationalSpecialPurposeVehicle { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_regulatedCharacteristicsExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType RegulatedCharacteristicsExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_EuVehicleCategoryEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EuVehicleCategoryEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public EuVehicleCategoryEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EuVehicleCategoryEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    public enum EuVehicleCategoryEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("m")]
        M,

        [System.Xml.Serialization.XmlEnumAttribute("m1")]
        M1,

        [System.Xml.Serialization.XmlEnumAttribute("m2")]
        M2,

        [System.Xml.Serialization.XmlEnumAttribute("m3")]
        M3,

        [System.Xml.Serialization.XmlEnumAttribute("n")]
        N,

        [System.Xml.Serialization.XmlEnumAttribute("n1")]
        N1,

        [System.Xml.Serialization.XmlEnumAttribute("n2")]
        N2,

        [System.Xml.Serialization.XmlEnumAttribute("n3")]
        N3,

        [System.Xml.Serialization.XmlEnumAttribute("o")]
        O,

        [System.Xml.Serialization.XmlEnumAttribute("o1")]
        O1,

        [System.Xml.Serialization.XmlEnumAttribute("o2")]
        O2,

        [System.Xml.Serialization.XmlEnumAttribute("o3")]
        O3,

        [System.Xml.Serialization.XmlEnumAttribute("o4")]
        O4,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_EuSpecialPurposeVehicleEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EuSpecialPurposeVehicleEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public EuSpecialPurposeVehicleEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EuSpecialPurposeVehicleEnum", Namespace = "http://datex2.eu/schema/3/commonExtension")]
    public enum EuSpecialPurposeVehicleEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("motorCaravan")]
        MotorCaravan,

        [System.Xml.Serialization.XmlEnumAttribute("armouredVehicle")]
        ArmouredVehicle,

        [System.Xml.Serialization.XmlEnumAttribute("ambulance")]
        Ambulance,

        [System.Xml.Serialization.XmlEnumAttribute("hearse")]
        Hearse,

        [System.Xml.Serialization.XmlEnumAttribute("trailerCaravan")]
        TrailerCaravan,

        [System.Xml.Serialization.XmlEnumAttribute("mobileCrane")]
        MobileCrane,

        [System.Xml.Serialization.XmlEnumAttribute("otherSpecialPurposeVehicle")]
        OtherSpecialPurposeVehicle,

        [System.Xml.Serialization.XmlEnumAttribute("wheelChairAccessibleVehicle")]
        WheelChairAccessibleVehicle,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }
}
