//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen DATEXII_3_EnergyInfrastructure.xsd -v --namespace http://datex2.eu/schema/3/common=Datex2ToOcpi.Core.Models.Datex2.Common --namespace http://datex2.eu/schema/3/commonExtension=Datex2ToOcpi.Core.Models.Datex2.CommonExtension --namespace http://datex2.eu/schema/3/facilities=Datex2ToOcpi.Core.Models.Datex2.Facilities --namespace http://datex2.eu/schema/3/energyInfrastructure=Datex2ToOcpi.Core.Models.Datex2.EnergyInfrastructure --namespace http://datex2.eu/schema/3/locationExtension=Datex2ToOcpi.Core.Models.Datex2.LocationExtension --namespace http://datex2.eu/schema/3/locationReferencing=Datex2ToOcpi.Core.Models.Datex2.LocationReferencing --namespace http://datex2.eu/schema/3/trafficRegulation=Datex2ToOcpi.Core.Models.Datex2.TrafficRegulation
namespace Datex2ToOcpi.Core.Models.Datex2.LocationExtension
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FacilityLocation", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FacilityLocation
    {

        /// <summary>
        /// <para xml:lang="en">Maximum length: 1024.</para>
        /// <para xml:lang="en">Pattern: [-+][0-9][0-9]:[0-9][0-9]|Z.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1024)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[-+][0-9][0-9]:[0-9][0-9]|Z")]
        [System.Xml.Serialization.XmlElementAttribute("timeZone")]
        public string TimeZone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Address", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address
    {

        /// <summary>
        /// <para xml:lang="en">Maximum length: 1024.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1024)]
        [System.Xml.Serialization.XmlElementAttribute("postcode")]
        public string Postcode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("city")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.MultilingualString City { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2)]
        [System.Xml.Serialization.XmlElementAttribute("countryCode")]
        public string CountryCode { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AddressLine> _addressLine;

        [System.Xml.Serialization.XmlElementAttribute("addressLine")]
        public System.Collections.ObjectModel.Collection<AddressLine> AddressLine
        {
            get
            {
                return _addressLine;
            }
            private set
            {
                _addressLine = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AddressLine collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressLineSpecified
        {
            get
            {
                return (this.AddressLine.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Address" /> class.</para>
        /// </summary>
        public Address()
        {
            this._addressLine = new System.Collections.ObjectModel.Collection<AddressLine>();
        }

        [System.Xml.Serialization.XmlElementAttribute("_addressExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType AddressExtension { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressLine", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressLine
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public AddressLineTypeEnum Type { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("text")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.MultilingualString Text { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("_addressLineExtension")]
        public Datex2ToOcpi.Core.Models.Datex2.Common.ExtensionType AddressLineExtension { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("order")]
        public string Order { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_AddressLineTypeEnum", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressLineTypeEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public AddressLineTypeEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressLineTypeEnum", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    public enum AddressLineTypeEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("apartment")]
        Apartment,

        [System.Xml.Serialization.XmlEnumAttribute("building")]
        Building,

        [System.Xml.Serialization.XmlEnumAttribute("poBox")]
        PoBox,

        [System.Xml.Serialization.XmlEnumAttribute("unit")]
        Unit,

        [System.Xml.Serialization.XmlEnumAttribute("region")]
        Region,

        [System.Xml.Serialization.XmlEnumAttribute("town")]
        Town,

        [System.Xml.Serialization.XmlEnumAttribute("districtTerritory")]
        DistrictTerritory,

        [System.Xml.Serialization.XmlEnumAttribute("floor")]
        Floor,

        [System.Xml.Serialization.XmlEnumAttribute("street")]
        Street,

        [System.Xml.Serialization.XmlEnumAttribute("houseNumber")]
        HouseNumber,

        [System.Xml.Serialization.XmlEnumAttribute("generalTextLine")]
        GeneralTextLine,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NamedAreaExtended", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NamedAreaExtended
    {

        /// <summary>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("namedAreaCode")]
        public string NamedAreaCode { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SupplementaryPositionalDescriptionExtended", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SupplementaryPositionalDescriptionExtended
    {

        [System.Xml.Serialization.XmlElementAttribute("houseNumberSide")]
        public HouseNumberSideEnum HouseNumberSide { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("_HouseNumberSideEnum", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HouseNumberSideEnum
    {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public HouseNumberSideEnum2 Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("_extendedValue")]
        public string ExtendedValue { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HouseNumberSideEnum", Namespace = "http://datex2.eu/schema/3/locationExtension")]
    public enum HouseNumberSideEnum2
    {

        [System.Xml.Serialization.XmlEnumAttribute("odd")]
        Odd,

        [System.Xml.Serialization.XmlEnumAttribute("even")]
        Even,

        [System.Xml.Serialization.XmlEnumAttribute("_extended")]
        Extended,
    }
}
